### 📌 What is NumPy?
NumPy (Numerical Python) is a Python library used for working with arrays and performing mathematical operations efficiently. It provides multi-dimensional arrays (ndarrays) and powerful mathematical functions to perform operations on large datasets faster than Python lists.

### 🔹 Why Do We Use NumPy?
- Faster Computation 🚀
  - NumPy arrays are much faster than Python lists because they use C under the hood.
- Memory Efficient 💾
  - NumPy stores data in a continuous block of memory, making operations faster.
- Supports Multi-Dimensional Arrays 🔢

  - You can create 1D, 2D, or even 3D arrays easily.
- Built-in Mathematical Functions ➕✖

  - NumPy provides many functions for matrices, statistics, and algebra.
- Used in Machine Learning & AI 🤖

  - Almost all ML libraries (pandas, scikit-learn, TensorFlow) use NumPy internally.

In [2]:
import numpy as np

## Datatypes and Attributes

In [19]:
# Numpy's main datatypes is ndarray
a1 = np.array([1,2,3,4,5])
a1

array([1, 2, 3, 4, 5])

In [20]:
type(a1)

numpy.ndarray

In [21]:
a2 = np.array(
    [
    [1,2,3.2,4,5],
    [3.4,5.6,7.8,6,1.2]
    ]
)
a2

array([[1. , 2. , 3.2, 4. , 5. ],
       [3.4, 5.6, 7.8, 6. , 1.2]])

In [22]:
a3 = np.array([[[1, 2, 3],
                [4, 5, 6]],
               [[7, 8, 9],
                [10, 11, 12]],
               [[13, 14, 15],
                [16, 17, 18]]])
a3


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [23]:
a1.shape, a2.shape, a3.shape
# (rows, columns, depth, ...)

((5,), (2, 5), (3, 2, 3))

In [24]:
# number of dimensions
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [25]:
# number of elements
a1.size, a2.size, a3.size

(5, 10, 18)

In [27]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [28]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

## Create a datafrom from numpy array

In [33]:
a2

array([[1. , 2. , 3.2, 4. , 5. ],
       [3.4, 5.6, 7.8, 6. , 1.2]])

In [32]:
import pandas as pd
df = pd.DataFrame(a2)
df

0    1    2    3    4
0  1.0  2.0  3.2  4.0  5.0
1  3.4  5.6  7.8  6.0  1.2

## Creating Arrays

In [1]:
sample_array = np.array([1,2,3,4,5])
sample_array

NameError: name 'np' is not defined

In [3]:
ones = np.ones(5)
ones

array([1., 1., 1., 1., 1.])

In [4]:
zeroes = np.zeros(5)
zeroes

array([0., 0., 0., 0., 0.])

In [5]:
ones = np.ones((2,3)) # 2 rows, 3 columns
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
range_array = np.arange(10)
range_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
range_array2 =np.arange(1,11,2)
range_array2

array([1, 3, 5, 7, 9])

## Random Array

In [10]:
random_array = np.random.randint(1,100, size=(3,3)) # 3 rows, 3 columns (1-100 exclusive)
random_array

array([[55, 43, 19],
       [81, 70, 88],
       [10, 24, 48]])

In [13]:
random_array3 = np.random.random((5,3)) # 5 rows, 3 columns (0-1)
random_array3

array([[0.72664421, 0.18360055, 0.26292636],
       [0.71533754, 0.97778045, 0.80792171],
       [0.04185601, 0.12161748, 0.35138955],
       [0.99285691, 0.66428335, 0.53206334],
       [0.34023286, 0.36379776, 0.29386912]])

In [14]:
random_array3.shape

(5, 3)

In [15]:
random_array4 = np.random.rand(5,3)
random_array4

array([[0.78983439, 0.80248447, 0.48072435],
       [0.61304075, 0.36557312, 0.54825057],
       [0.68642109, 0.36632438, 0.84306151],
       [0.33772825, 0.05038785, 0.39212813],
       [0.67670771, 0.38408378, 0.32212878]])

## Numpy Random Seed